{{- if .Values.camelDigest }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-digest
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ccm-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  camel-k-digest: {{ .Values.camelDigest | quote }}
{{- end }}
