apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ccm-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ccm-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "ccm-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ccm-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{ toJson .Values.command }}
          {{- end }}
          {{- if .Values.args }}
          args: {{ toJson .Values.args }}
          {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: "{{ .value }}"
              {{- else if .valueFrom }}
              valueFrom:
                {{ toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
          ports:
            {{- if .Values.container.ports }}
            {{- range .Values.container.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
            {{- end }}
          volumeMounts:
            {{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
            {{- end }}
          {{- if .Values.container.resources }}
          resources:
            {{ toYaml .Values.container.resources | nindent 12 }}
          {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          {{- if .configMap }}
          configMap: {{ toYaml .configMap | nindent 12 }}
          {{- else if .secret }}
          secret: {{ toYaml .secret | nindent 12 }}
          {{- else if .emptyDir }}
          emptyDir: {{ toYaml .emptyDir | nindent 12 }}
          {{- end }}
        {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
      maxSurge: {{ .Values.strategy.maxSurge }}
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
