apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccm-app.fullname" . }}-secret
  labels:
    {{- include "ccm-app.labels" . | nindent 4 }}
type: Opaque
data:
  key1: {{ .Values.secret.key1 | b64enc }}