apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cef5dd-test
  name: 'ccm-accessdedup-processor'
  annotations: {}
spec:
  selector:
    matchLabels:
      app: jade-ccm
  replicas: 1
  template:
    metadata:
      labels:
        app: jade-ccm
        deployer: agahchen
    spec:
      containers:
        - name: container
          image: >-
            image-registry.openshift-image-registry.svc:5000/cef5dd-test/ccm-accessdedup-processor:latest
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
