apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: deployment-template
parameters:
- name: NAMESPACE
  description: The namespace for the deployment
  required: true
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: ${NAMESPACE}
    name: ccm-pidp-adapter-quarkus
  spec:
    selector:
      matchLabels:
        app: jade-ccm
    replicas: 1
    template:
      metadata:
        labels:
          app: jade-ccm
          pod-name: ccm-pidp-adapter-quarkus 
        name: ccm-pidp-adapter-quarkus
      spec:
        containers:
        - name: container
          image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/ccm-pidp-adapter-quarkus:latest
          imagePullPolicy: Always
          env:
          - name: TZ
            value: Canada/Pacific
          - name: KAFKA-BROKER-URL
            value: events-kafka-bootstrap:9092
          envFrom:
          - configMapRef:
              name: ccm-configs
          - secretRef:
              name: ccm-secrets
          volumeMounts:
          - name: pidp-kafka-client-p12-volume
            mountPath: /etc/keystore/pidp-kafka-client.p12
            subPath: pidp-kafka-client.p12
          - name: pidp-kafka-server-p12-volume
            mountPath: /etc/keystore/pidp-kafka-server.p12
            subPath: pidp-kafka-server.p12
        imagePullSecrets: []
        volumes:
        - name: pidp-kafka-client-p12-volume
          configMap:
            name: ccm-configs
        - name: pidp-kafka-server-p12-volume
          configMap:
            name: ccm-configs
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    paused: false