camel.main.sourceLocationEnabled=true
camel.main.modeline=true
camel.jbang.health=false
camel.jbang.console=false
camel.jbang.camel-version=3.20.5
camel.jbang.dependencies=ccm:ccm-models:0.0.1-SNAPSHOT
