# Point-in-time restore backup of ccm-quarkus-configs
# Namespace: cef5dd-dev   Captured: 2026-07-30
# Re-apply with: oc apply -f $(basename "$0") -n cef5dd-dev
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccm-quarkus-configs
  namespace: cef5dd-dev
  labels:
    app: jade-ccm
data:
  dems-case-auto-creation: "true"
  dems-case-auto-creation-submit-date-cutoff: "1965"
  dems-case-hyperlink-prefix: "https://dems.dev.jag.gov.bc.ca/Edt.aspx#/cases/"
  dems-case-hyperlink-suffix: "/case-file/1-1-entire-file-all-columns"
  dems-case-hyperlinklist-suffix: "/court-file--vcf/1--front-end-court"
  dems-case-template-id: "28"
  dems-host-url: "wsgw.dev.jag.gov.bc.ca/bcpsdems/api/v1"
  dems-org-unit-id: "1"
  justin-disable-file-notes-processing: "false"
  justin-host-url: "wsgw.dev.jag.gov.bc.ca/justin/dems/api/v1"
  kafka-broker-url: "events-kafka-bootstrap:9092"
  kafka-streams-bootstrap-servers: "events-kafka-bootstrap:9093"
  pidp-api-host: "https://diam-islinterfaces-e27db1-test.apps.gold.devops.gov.bc.ca/api/v1/"
  pidp-api-oauth-client-id: "jade-ccm-webapi-client"
  pidp-api-oauth-token-endpoint-url: "test.common-sso.justice.gov.bc.ca/auth/realms/BCPS/protocol/openid-connect/token"
  pidp-api-oauth-token-endpoint-url-tst: "dev.common-sso.justice.gov.bc.ca/auth/realms/BCPS/protocol/openid-connect/token"
  pidp-kafka-apicurioregistry-url: "https://pidp-apicurio-5b7aa5-test.apps.silver.devops.gov.bc.ca/apis/ccompat/v6"
  pidp-kafka-bootstrapservers-url: "diam-kafka-test-a239c6-test.apps.gold.devops.gov.bc.ca:443"
  pidp-kafka-oauth-client-id: "digitalevidence-jade-ccm-consumer"
  pidp-kafka-oauth-token-endpoint-url: "https://test.common-sso.justice.gov.bc.ca/auth/realms/Kafka/protocol/openid-connect/token"
  pidp-kafka-topic-participantmerge-name: "digitalevidence-justin-participant-merge-topic"
  pidp-kafka-topic-processresponse-name: "digitalevidence-processresponse-topic"
  pidp-kafka-topic-usercreation-name: "digitalevidence-usercreation-plain-topic"
  quarkus.kafka-streams.bootstrap-servers: "events-kafka-bootstrap:9092"
  quarkus.kafka-streams.ssl.truststore.location: "/etc/kafka-certs/ca.crt"
  quarkus.kafka-streams.ssl.truststore.type: "PEM"
  splunk-host-url: "hec.monitoring.ag.gov.bc.ca:8088/services/collector"
  topic-bulk-chargeassessment-consumer-count: "5"
  topic-chargeassessment-consumer-count: "3"
  topic-courtcase-consumer-count: "3"
