# GitOpsTeam - create this CRD in your tools namespace in order to enable
# Argo CD for your project
apiVersion: warden.devops.gov.bc.ca/v1alpha1
kind: GitOpsTeam
metadata:
  name: gitopsteam-cef5dd
  namespace: cef5dd-tools
spec:
  # gitOpsMembers defines the git repo access (tenant-gitops-XYZ)
  # Note that us
  # -----------------------------------------------------------------------
  gitOpsMembers:

    # Full admin access to the repo, including repo deletion, adding of users
    # Recommended for people who need full access to the project, including
    # sensitive and destructive actions like managing security or deleting a
    # repository.
    admins:
      - jennifer-dowd@github
      - agahchen@github

    # Recommended for contributors who actively push to your project.
    writers:

    # Recommended for project managers who need to manage the repository without
    # access to sensitive or destructive actions.
    maintainers:

    # Recommended for non-code contributors who want to view or discuss your
    # project.
    readers:

    # Recommended for contributors who need to manage issues and pull requests
    # without write access.
    triage:

  # projectMembers defines access to the Argo CD UI
  # -----------------------------------------------
  projectMembers:

    # Project Maintainers have full access to the Argo CD Project, including the
    # ability create, edit, and delete Applications within the Project
    maintainers:
      - jennifer-dowd@github
      - agahchen@github

    # Project Readers have read-only access to the Project in the Argo CD UI
    readers:
