quarkus.kafka.devservices.enabled=false
quarkus.kafka-streams.bootstrap-servers=${KAFKA-BROKER-URL:events_broker:9093}

quarkus.openshift.image-stream.name=ccm-justin-in-adapter
quarkus.kubernetes.deployment-kind=StatefulSet
quarkus.kubernetes.name=ccm-justin-in-adapter
quarkus.kubernetes.replicas=1
quarkus.log.console.color=true


justin.in.token = {{justin-in-security-token}}

dems.case.hyperlink.prefix = {{dems-case-hyperlink-prefix}}
dems.case.hyperlink.suffix = {{dems-case-hyperlink-suffix}}

ccm.application.name.propercase = CcmJustinInAdapter