kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
spec:
  podSelector:
    matchLabels:
      strimzi.io/name: events-zookeeper
  ingress:
    - ports:
        - protocol: TCP
          port: 2888
        - protocol: TCP
          port: 3888
      from:
        - podSelector:
            matchLabels:
              strimzi.io/name: events-zookeeper
    - ports:
        - protocol: TCP
          port: 2181
      from:
        - podSelector:
            matchLabels:
              strimzi.io/name: events-kafka
        - podSelector:
            matchLabels:
              strimzi.io/name: events-zookeeper
        - podSelector:
            matchLabels:
              strimzi.io/name: events-entity-operator
        - podSelector:
            matchLabels:
              strimzi.io/kind: cluster-operator
          namespaceSelector: {}
        - podSelector:
            matchLabels:
              strimzi.io/name: events-cruise-control
  policyTypes:
    - Ingress
