@startuml
'https://plantuml.com/state-diagram

title
DEMS Case State Diagram (BCPSDEMS-375 5.2.3 Merge Cases)

end title

[*] --> created : [Event] CourtCase.CREATED\n("AGEN_FILE")
state "Created" as created {
  state "Before Approval for Trial" as preapproval
  [*] --> preapproval
  preapproval --> preapproval : [Event] CourtCase.UPDATED\n("AGEN_FILE")
}
created --> approved : [Event] CourtCaseMetadata.CHANGED\n("COURT_FILE")
state "Approved for Trial" as approved {
  [*] --> approved_primary : Primary RCC
  [*] --> approved_sub : Sub (merged) RCC
  [*] --> approved_only : Only RCC
  state "Primary Active (Approved) Case" as approved_primary {
    approved_primary : agency file id = <This RCC ID>
    approved_primary : primary y/n = yes
    approved_primary : primary rcc = none
  }
  state "Subordinate Inactive (Merged) Case" as approved_sub {
    approved_sub : agency file id = <This RCC ID>
    approved_sub : primary y/n = no
    approved_sub : primary rcc = <Primary RCC ID>
  }
  state "Only Active (Approved) Case" as approved_only {
    approved_only : agency file id = <This RCC ID>
    approved_only : primary y/n = yes
    approved_only : primary rcc = none
    approved_only : --
    approved_only : This is identical to "Primary Active (Approved) Case"?
  }
}
approved --> [*]

caption

Prepared by David Agahchen | Updated October 6 (Rev 1), 2022
end caption
@enduml