@startuml
hide footbox
participant j_mock as "JUSTIN"
participant j_utility_adapter as "JUSTIN Utility Adapter"
queue court_file_created as "Court File Created (event topic)"
participant d_edge_adapter as "DEMS Edge Adapter"
participant d_mock as "DEMS"
j_mock -> j_utility_adapter: New court file available
j_utility_adapter -> court_file_created: Produce court file created event
d_edge_adapter --> court_file_created: Consume court file created event
d_edge_adapter -> d_mock: Push court file into DEMS
@enduml