@startuml
'hide footbox

skinparam Shadowing true
skinparam CollectionsBackgroundColor Lavender
skinparam ControlBackgroundColor LightSkyBlue
skinparam BoundaryBackgroundColor LightGrey

/' 
Available colours
https://plantuml-documentation.readthedocs.io/en/latest/formatting/color-names.html
'/

boundary j_interface as "JUSTIN Interface"
control j_adapter as "JUSTIN Adapter"
collections charge_assessment_cases_topic as "Charge Assessment Case Events"
collections court_cases_topic as "Court Case Events"
collections case_users_topic as "Case User Events"
collections bulk_case_users_topic as "Bulk Case User Events"
collections reports_topic as "Report Events"

title
CCM JUSTIN Event Processing Sequence Diagram
end title

autonumber

activate j_adapter

par Parallel Main Processing

    loop Every 5 minutes
        j_adapter-> j_interface: Retrieve a new batch of JUSTIN events from Main Queue
        activate j_interface
        j_interface --> j_adapter: List of JUSTIN events from Main Queue
        j_adapter-> j_interface: Retrieve all in progress JUSTIN events from Main Queue
        j_interface --> j_adapter: List of JUSTIN events from Main Queue
        deactivate j_interface

        loop While there are JUSTIN events
            loop For every JUSTIN event
                j_adapter -> j_adapter: Convert data from System (JUSTIN) to Business model
                alt MANU_FILE
                    j_adapter ->o charge_assessment_cases_topic: Produce MANUALLY_CHANGED event
                else AGEN_FILE
                    j_adapter ->o charge_assessment_cases_topic: Produce CHANGED event
                else AUTH_LIST
                    j_adapter ->o charge_assessment_cases_topic: Produce AUTH_LIST_CHANGED event
                else COURT_FILE
                    j_adapter ->o court_cases_topic: Produce CHANGED event
                else APPR
                    j_adapter ->o court_cases_topic: Produce APPEARANCE_CHANGED event
                else CRN_ASSIGN
                    j_adapter ->o court_cases_topic: Produce CROWN_ASSIGNMENT_CHANGED event
                else REPORT
                    j_adapter ->o reports_topic: <font color=grey>Produce REPORT event (Disabled)</font>
                else DOCM
                    j_adapter ->o reports_topic: <font color=grey>Produce DOCM event (Disabled)</font>
                else Unknown JUSTIN Event
                    j_adapter -> j_adapter: No operation (future functionality)
                end
                j_adapter -> j_interface: Mark event as processed
                activate j_interface
                j_interface --> j_adapter: Acknowledgement
                deactivate j_interface
            end

            j_adapter-> j_interface: Retrieve new batch of JUSTIN events from Main Queue
            activate j_interface
            j_interface --> j_adapter: List of JUSTIN events from Main Queue
            deactivate j_interface
        end
    end

else Parallel Bulk Processing

    loop Every 5 minutes
        j_adapter-> j_interface: Retrieve a new batch of JUSTIN events from Bulk Queue
        activate j_interface
        j_interface --> j_adapter: List of JUSTIN events from Bulk Queue
        j_adapter-> j_interface: Retrieve all in progress JUSTIN events from Bulk Queue
        j_interface --> j_adapter: List of JUSTIN events from Bulk Queue
        deactivate j_interface

        loop While there are JUSTIN events
            loop For every JUSTIN event
                j_adapter -> j_adapter: Convert data from System (JUSTIN) to Business model
                alt USER_PROV
                    j_adapter ->o bulk_case_users_topic: Produce ACCESS_ADDED event
                else USER_DPROV
                    j_adapter ->o bulk_case_users_topic: Produce ACCESS_REMOVED event
                end
                j_adapter -> j_interface: Mark event as processed
                activate j_interface
                j_interface --> j_adapter: Acknowledgement
                deactivate j_interface
            end

            j_adapter-> j_interface: Retrieve new batch of JUSTIN events from Bulk Queue
            activate j_interface
            j_interface --> j_adapter: List of JUSTIN events from Bulk Queue
            deactivate j_interface
        end
    end

    alt Total number of events in batch > 0
        j_adapter ->o bulk_case_users_topic : Produce EVENT_BATCH_ENDED event
    end
end
deactivate j_adapter

caption
Prepared by David Agahchen | Updated December 6, 2023
end caption
@enduml