@startuml
'hide footbox

skinparam Shadowing true
skinparam CollectionsBackgroundColor Lavender
skinparam ControlBackgroundColor LightSkyBlue
skinparam BoundaryBackgroundColor LightGrey

/' 
Available colours
https://plantuml-documentation.readthedocs.io/en/latest/formatting/color-names.html
'/

collections case_users_topic as "Case User Events"
control notification_service as "Notification Service"
collections bulk_case_users_topic as "Bulk Case User Events"
control accessdedup_processor as "AccessDedup Processor"
collections case_access_sync_store as "Case Access Sync Store"

title
CCM Case User ACCESS_REMOVED Event Processing Sequence Diagram
end title

autonumber

case_users_topic o-> notification_service : Process ACCESS_REMOVED event
activate notification_service
notification_service ->o bulk_case_users_topic : Redirect event to the bulk topic
deactivate notification_service

bulk_case_users_topic o-> accessdedup_processor : Process ACCESS_REMOVED event
activate accessdedup_processor

accessdedup_processor -> case_access_sync_store: Query for case number

alt Case not in store
    accessdedup_processor -> accessdedup_processor: Derive case number from event
    accessdedup_processor ->o case_access_sync_store: Store INFERRED_AUTH_LIST_CHANGED charge assessment event
else Case already in store
    accessdedup_processor -> accessdedup_processor: Ignore event
end

deactivate accessdedup_processor

caption
Prepared by David Agahchen | Updated December 6, 2023
end caption
@enduml