@startuml
'hide footbox

skinparam Shadowing true
skinparam CollectionsBackgroundColor Lavender
skinparam ControlBackgroundColor LightSkyBlue
skinparam BoundaryBackgroundColor LightGrey


/' 
Available colours
https://plantuml-documentation.readthedocs.io/en/latest/formatting/color-names.html
'/

boundary j_interface as "JUSTIN Interface"
control j_adapter as "JUSTIN Adapter"
collections approved_court_cases_topic as "Approved Court Case Events"
collections errors_topic as "Approved Court Case Event Errors"
collections kpis_topic as "Event KPIs"
control notification_service as "Notification Service"
control lookup_service as "Lookup Service"
control d_adapter as "DEMS Adapter"
boundary d_interface as "DEMS Interface"

title
CCM Approved Court Case MANUALLY_CHANGED Event Processing Sequence Diagram
end title

approved_court_cases_topic o-> notification_service: Process court case MANUALLY_CHANGED event
activate notification_service

notification_service ->o kpis_topic: **[1]** Publish 'processing started' event KPI

notification_service -> lookup_service: **[2]** Check case exists
activate lookup_service

lookup_service -> d_adapter: **[2.1]** Check case existence in DEMS
activate d_adapter
d_adapter -> d_adapter: **[2.1.1]** Convert data from Business to System (DEMS) model


break#LightCoral 2.1.1 - Data error
    notification_service ->o errors_topic: Publish event with error
    notification_service ->o kpis_topic: Publish 'processing failed' event KPI
end break

d_adapter -> d_interface: **[2.1.2]** Check case existence in DEMS
activate d_interface

break#LightCoral 2.1.2 - HTTP Client Side Error (400 series)
    d_interface --> d_adapter: HTTP Client Side Error (400 series)
    d_adapter --> notification_service: HTTP Client Side Error (400 series)
    notification_service ->o errors_topic: Publish event with error
    notification_service ->o kpis_topic: Publish 'processing failed' event KPI
end break

group#Khaki warning [2.1.2 - HTTP Server Side Error (500 series)]
    d_interface --> d_adapter: HTTP Server Side Error (500 series)
    d_adapter --> notification_service: HTTP Server Side Error (500 series)
    alt Short term retries
        notification_service -> notification_service: Connection retry
    else Restart event processing
        notification_service ->o kpis_topic: Publish 'processing warning' event KPI
        notification_service -> notification_service: Re-process event
    end
end group

d_interface --> d_adapter: Response
deactivate d_interface
d_adapter --> lookup_service: Response
deactivate d_adapter
lookup_service --> notification_service: Response
deactivate lookup_service
alt New court case
    notification_service ->o approved_court_cases_topic: **[3]** Produce court case CREATED event
else Existing court case
    notification_service ->o approved_court_cases_topic: **[4]** Produce court case UPDATED event
end

notification_service ->o kpis_topic: **[5]** Publish 'processing completed' event KPI

deactivate notification_service

caption
Prepared by David Agahchen | Updated December 19, 2022
end caption
@enduml