@startuml
'hide footbox

skinparam Shadowing true
skinparam CollectionsBackgroundColor Lavender
skinparam ControlBackgroundColor LightSkyBlue
skinparam BoundaryBackgroundColor LightGrey

/' 
Available colours
https://plantuml-documentation.readthedocs.io/en/latest/formatting/color-names.html
'/

database justin_db as "JUSTIN Database"
boundary zb_interface as "ZoneB Proxy"
control ji_adapter as "JUSTIN In Adapter"
control lookup_service as "Lookup Service"
control d_adapter as "DEMS Adapter"
boundary d_interface as "DEMS Interface"

title
CCM Charge Assessment Get Case Hyperlink Processing Sequence Diagram
end title

autonumber

activate justin_db
justin_db -> zb_interface: Get case hyperlink by RCC id
activate zb_interface

zb_interface -> ji_adapter: Get case hyperlink by RCC id
activate ji_adapter

break Not authenticated (HTTP 401)
    ji_adapter --> justin_db: Error Response (converted)
end break

ji_adapter -> ji_adapter: Convert data from System (JUSTIN) to Business model
ji_adapter -> lookup_service: Get case hyperlink by charge asessment key

activate lookup_service
lookup_service -> d_adapter: Get case hyperlink by charge asessment key

activate d_adapter
d_adapter -> d_adapter: Convert data from Business to System (DEMS) model
d_adapter -> d_interface: Get case id by case key

activate d_interface

break RCC not found (HTTP 404)
    d_interface --> justin_db: Error Response (converted)
end break

d_interface -> d_adapter: DEMS case id
deactivate d_interface

d_adapter -> d_adapter: Convert data from System (DEMS) to Business model
d_adapter -> lookup_service: Case hyperlink
deactivate d_adapter

lookup_service -> ji_adapter: Case hyperlink
deactivate lookup_service

ji_adapter -> ji_adapter: Convert data from Business to System (JUSTIN) model
ji_adapter -> zb_interface: Case hyperlink

deactivate ji_adapter
zb_interface -> justin_db: Case hyperlink

caption
Prepared by David Agahchen | Updated May 3, 2023
end caption
@enduml