@startuml
'hide footbox

skinparam Shadowing true
skinparam CollectionsBackgroundColor Lavender
skinparam ControlBackgroundColor LightSkyBlue
skinparam BoundaryBackgroundColor LightGrey 

/' 
Available colours
https://plantuml-documentation.readthedocs.io/en/latest/formatting/color-names.html
'/

boundary j_interface as "JUSTIN Interface"
control j_adapter as "JUSTIN Out Adapter"
collections inferred_file_note_topic as "File Note Events"
control notification_service as "Notification Service"
control lookup_service as "Lookup Service"

title
CCM File Note Delete Event Processing Sequence Diagram
end title

autonumber

inferred_file_note_topic o-> notification_service : Process DEL_FNOTE event
activate notification_service

group Call route processFileNoteDelete
notification_service -> lookup_service : Retrieve File Note
activate lookup_service

lookup_service -> j_adapter : Retrieve file note
activate j_adapter

j_adapter -> JUSTIN : retrieve file note by id
activate JUSTIN
j_adapter->notification_service : return file note

notification_service-> notification_service : print out file note id
end group


deactivate notification_service
deactivate lookup_service
deactivate j_adapter
deactivate j_interface

caption
Prepared by Todd Wuolle | Updated August 20, 2024
end caption
@enduml