apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ccm-app.fullname" . }}
  labels:
    {{- include "ccm-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ccm-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ccm-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: CONFIG_KEY1
              value: {{ .Values.config.key1 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
