name: ccm-justin-in-adapter
namespace: <PLACEHOLDER_NAMESPACE>
replicas: 1

labels:
  integration: ccm-justin-in-adapter
  camel_generation: "1"

annotations:
  operator_id: camel-k

image:
  registry: image-registry.openshift-image-registry.svc:5000
  namespace: <PLACEHOLDER_NAMESPACE>
  name: camel-k-kit-ct8vil7mil8713q5olgg
  tag: sha256:44d339d83e995bac23a939d49eb3b135a31d57f45f56322df2ac6baf48b3e1de
  pullPolicy: IfNotPresent

container:
  name: integration
  command:
    - /bin/sh
    - -c
  args:
    - echo exec java -cp ./...
  workingDir: /deployments
  resources:
    requests:
      cpu: 5m
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP

env:
  - name: CAMEL_K_DIGEST
    value: vUkyA-7dJcQy8wUzo9uqpuA_vAfTVG4x_dit9JqXSHOQ
  - name: CAMEL_K_CONF
    value: /etc/camel/application.properties
  - name: CAMEL_K_CONF_D
    value: /etc/camel/conf.d
  - name: CAMEL_K_VERSION
    value: 1.10.8
  - name: CAMEL_K_OPERATOR_ID
    value: camel-k
  - name: CAMEL_K_INTEGRATION
    value: ccm-justin-in-adapter
  - name: CAMEL_K_RUNTIME_VERSION
    value: 1.15.6.redhat-00051
  - name: CAMEL_K_MOUNT_PATH_CONFIGMAPS
    value: /etc/camel/conf.d/_configmaps
  - name: CAMEL_K_MOUNT_PATH_SECRETS
    value: /etc/camel/conf.d/_secrets
  - name: NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: TZ
    value: Canada/Pacific
  - name: QUARKUS_LOG_LEVEL
    value: INFO
  - name: QUARKUS_LOG_CONSOLE_JSON
    value: "false"
  - name: QUARKUS_LOG_CONSOLE_COLOR
    value: "true"

volumes:
  - name: i-source-000
    configMap:
      name: ccm-justin-in-adapter-source-000
      items:
        - key: content
          path: CcmJustinInAdapter.java
  - name: user-properties
    configMap:
      name: ccm-justin-in-adapter-user-properties
      items:
        - key: application.properties
          path: user.properties
  - name: application-properties
    configMap:
      name: ccm-justin-in-adapter-application-properties
      items:
        - key: application.properties
          path: application.properties
  - name: ccm-configs
    configMap:
      name: ccm-configs
  - name: ccm-secrets
    secret:
      secretName: ccm-secrets
  - name: cm-e4a878280d6fd53f812a691359b9fb1afdea4f23
    configMap:
      name: cm-e4a878280d6fd53f812a691359b9fb1afdea4f23
      items:
        - key: ccm-models.jar
          path: ccm-models.jar

volumeMounts:
  - name: i-source-000
    mountPath: /etc/camel/sources/CcmJustinInAdapter.java
    subPath: CcmJustinInAdapter.java
    readOnly: true
  - name: user-properties
    mountPath: /etc/camel/conf.d/user.properties
    subPath: user.properties
    readOnly: true
  - name: application-properties
    mountPath: /etc/camel/application.properties
    subPath: application.properties
    readOnly: true
  - name: ccm-configs
    mountPath: /etc/camel/conf.d/_configmaps/ccm-configs
    readOnly: true
  - name: ccm-secrets
    mountPath: /etc/camel/conf.d/_secrets/ccm-secrets
    readOnly: true
  - name: cm-e4a878280d6fd53f812a691359b9fb1afdea4f23
    mountPath: /etc/camel/resources/ccm-models.jar
    subPath: ccm-models.jar
    readOnly: true
