name: ccm-justin-out-adapter
namespace: ""
replicas: 1

labels:
  integration: ccm-justin-out-adapter
  camel_generation: "1"

annotations:
  operator_id: camel-k

service:
  type: ClusterIP
  port: 80

strategy:
  maxUnavailable: 25%
  maxSurge: 25%

image:
  registry: image-registry.openshift-image-registry.svc:5000
  namespace: ""
  name: ccm-justin-out-adapter
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

container:
  name: integration
  command:
    - /bin/sh
    - -c
  args:
    - echo exec java -Xmx525M -cp ./...
  workingDir: /deployments
  resources:
    requests:
      cpu: 5m
      memory: 500Mi
    limits:
      cpu: 200m
      memory: 1000Mi
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP

env:
  - name: CAMEL_K_DIGEST
    value: vuQvYT7u4O7jL2MHbVqwHum2LHXDvk7ML_0OP0IrHXs0
  - name: CAMEL_K_CONF
    value: /etc/camel/application.properties
  - name: CAMEL_K_CONF_D
    value: /etc/camel/conf.d
  - name: CAMEL_K_VERSION
    value: 1.10.8
  - name: CAMEL_K_OPERATOR_ID
    value: camel-k
  - name: CAMEL_K_INTEGRATION
    value: ccm-justin-out-adapter
  - name: CAMEL_K_RUNTIME_VERSION
    value: 1.15.6.redhat-00051
  - name: CAMEL_K_MOUNT_PATH_CONFIGMAPS
    value: /etc/camel/conf.d/_configmaps
  - name: CAMEL_K_MOUNT_PATH_SECRETS
    value: /etc/camel/conf.d/_secrets
  - name: NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: TZ
    value: Canada/Pacific
  - name: QUARKUS_LOG_LEVEL
    value: INFO
  - name: QUARKUS_LOG_CONSOLE_JSON
    value: "false"
  - name: QUARKUS_LOG_CONSOLE_COLOR
    value: "true"

envFrom:
  - configMapRef:
      name: ccm-quarkus-configs
  - secretRef:
      name: ccm-quarkus-secrets

volumes: []
volumeMounts: []