apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-sa-binding
  namespace: foo-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: somerole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: my-sa
  namespace: foo-tools
