camel.main.sourceLocationEnabled=true
camel.main.modeline=true
camel.jbang.health=false
camel.jbang.console=false
camel.jbang.camel-version=3.20.4
camel.jbang.dependencies=ccm:ccm-models:0.0.1-SNAPSHOT
dependency=mvn:ccm:ccm-models:0.0.1-SNAPSHOT
dependency=mvn:org.apache.camel:camel-kamelet:3.20.4
dependency=mvn:org.apache.camel:camel-rest:3.20.4
dependency=mvn:org.apache.camel:camel-core-languages:3.20.4
