name: Deploy Quarkus App to OpenShift

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the application to deploy'
        required: true
        type: choice
        options:
          - redeploy-camel-simple
          - redeploy-dems-useraccess-adapter
      env:
        description: 'Select the environment'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}

    env:
      APP: ${{ github.event.inputs.app }}
      ENV: ${{ github.event.inputs.env }}
      NS: cef5dd-${{ github.event.inputs.env }}
      OCP_SERVER: ${{ secrets.OCP_SERVER }}
      OCP_TOKEN: ${{ secrets.OCP_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install OpenShift CLI (oc)
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz -o oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/
          oc version --client

      - name: Login to OpenShift
        run: |
          oc login $OCP_SERVER --token=$OCP_TOKEN
          oc project $NS

      # Build for camel-simple
      - name: Build Quarkus app - camel-simple
        if: env.APP == 'redeploy-camel-simple'
        working-directory: QuarkusInvestigation/camel-simple
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests -Dquarkus.kubernetes.deploy=true

      # Deploy for camel-simple
      - name: Deploy Kubernetes manifests - camel-simple
        if: env.APP == 'redeploy-camel-simple'
        run: |
          oc apply -f QuarkusInvestigation/camel-simple/target/kubernetes/kubernetes.yml -n $NS

      # Build for dems-useraccess-adapter
      - name: Build Quarkus app - DemsUserAccessAdapter
        if: env.APP == 'redeploy-dems-useraccess-adapter'
        working-directory: QuarkusInvestigation/DemsUserAccessAdapter
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests -Dquarkus.kubernetes.deploy=true

      # Deploy for dems-useraccess-adapter
      - name: Deploy Kubernetes manifests - DemsUserAccessAdapter
        if: env.APP == 'redeploy-dems-useraccess-adapter'
        run: |
          oc apply -f QuarkusInvestigation/DemsUserAccessAdapter/target/kubernetes/kubernetes.yml -n $NS
